import discord
from discord.ext import commands
from discord import app_commands
import google.generativeai as genai
import os
import datetime

# --- KONFIGURASI ---
TOKEN = os.getenv('TOKEN')
GEMINI_API_KEY = "AIzaSyCl1ScXm0tpiGISw-Cx21LYkJU8P4F6icE"

genai.configure(api_key=GEMINI_API_KEY)
ai_model = genai.GenerativeModel('gemini-1.5-flash')

class TatangCS(commands.Bot):
    def __init__(self):
        intents = discord.Intents.default()
        intents.message_content = True
        super().__init__(command_prefix='!', intents=intents)

    async def setup_hook(self):
        await self.tree.sync()
        print(f"✔️ Tatang CS Engine v3.0 Synced!")

bot = TatangCS()

# --- STEP 3: FORM MODAL DETAIL (SESUAI SCREENSHOT) ---
class CSDetailModal(discord.ui.Modal):
    def __init__(self, server, side, data_awal):
        super().__init__(title=f"Detail Cerita ({side})")
        self.server = server
        self.side = side
        self.data_awal = data_awal # Nama, Level, JK, Tgl Lahir, Kota Asal

        # Field tambahan sesuai screenshot (Halaman 2/2)
        self.bakat = discord.ui.TextInput(
            label="Bakat/Keahlian Dominan Karakter",
            placeholder="Contoh: Penembak jitu, negosiator ulung, supir ahli...",
            required=True
        )
        self.kultur = discord.ui.TextInput(
            label="Kultur/Etnis (Opsional)",
            placeholder="Contoh: African-American, Hispanic, Asian...",
            required=False
        )
        self.tambahan = discord.ui.TextInput(
            label="Detail Tambahan (Opsional)",
            placeholder="Contoh: Punya hutang, dikhianati geng lama, cita-cita...",
            style=discord.TextStyle.paragraph,
            max_length=4000,
            required=False
        )
        
        self.add_item(self.bakat)
        self.add_item(self.kultur)
        self.add_item(self.tambahan)

    async def on_submit(self, interaction: discord.Interaction):
        await interaction.response.send_message(f"⌛ **AI sedang menyusun cerita untuk {self.server}...**", ephemeral=True)
        
        # PROMPT SAKTI UNTUK ALUR PANJANG & SPESIFIK
        prompt = f"""
        Buatkan Character Story GTA SAMP untuk server {self.server}.
        Karakter ini berada di sisi: {self.side}
        
        DATA KARAKTER:
        - Nama: {self.data_awal['nama']}
        - Level: {self.data_awal['level']}
        - Gender: {self.data_awal['jk']}
        - Tanggal Lahir: {self.data_awal['tgl']}
        - Kota Asal: {self.data_awal['asal']}
        - Keahlian: {self.bakat.value}
        - Etnis: {self.kultur.value if self.kultur.value else 'Umum'}
        - Background Khusus: {self.tambahan.value if self.tambahan.value else 'Merantau ke Los Santos'}

        KETENTUAN:
        1. Minimal 500 kata, 3-4 paragraf.
        2. Gunakan bahasa Indonesia yang sangat rapi dan literasi tinggi.
        3. Sesuaikan suasana cerita dengan sisi {self.side}.
        4. Output WAJIB BBCode Forum ([justify], [center], [b], [i]).
        5. Watermark: -- Generated by Tatang AI for {self.server} --
        """

        try:
            response = ai_model.generate_content(prompt)
            cerita = response.text
            
            embed = discord.Embed(
                title=f"✅ CS Selesai - {self.server}",
                description=f"Berhasil membuat cerita untuk **{self.data_awal['nama']}** ({self.side})",
                color=0x00ff88
            )
            embed.set_footer(text="Tatang AI Engine v3.0")
            
            await interaction.followup.send(embed=embed)
            await interaction.followup.send(f"```bbcode\n{cerita}\n```")
        except Exception as e:
            await interaction.followup.send(f"❌ Terjadi kesalahan: {e}")

# --- STEP 2: FORM MODAL UTAMA (BIODATA) ---
class CSMainModal(discord.ui.Modal, title="Form Character Story (1/2)"):
    nama = discord.ui.TextInput(label="Nama Lengkap Karakter (IC)", placeholder="Contoh: John_Washington")
    level = discord.ui.TextInput(label="Level Karakter", placeholder="Contoh: 1")
    jk = discord.ui.TextInput(label="Jenis Kelamin", placeholder="Contoh: Laki-laki / Perempuan")
    tgl = discord.ui.TextInput(label="Tanggal Lahir", placeholder="Contoh: 17 Agustus 1995")
    asal = discord.ui.TextInput(label="Kota Asal", placeholder="Contoh: Chicago, Illinois")

    def __init__(self, server, side):
        super().__init__()
        self.server = server
        self.side = side

    async def on_submit(self, interaction: discord.Interaction):
        data_awal = {
            "nama": self.nama.value,
            "level": self.level.value,
            "jk": self.jk.value,
            "tgl": self.tgl.value,
            "asal": self.asal.value
        }
        # Lanjut ke form halaman 2
        await interaction.response.send_modal(CSDetailModal(self.server, self.side, data_awal))

# --- STEP 1: PILIH ALUR (GOOD/BADSIDE) ---
class CSAlurView(discord.ui.View):
    def __init__(self, server):
        super().__init__(timeout=60)
        self.server = server

    @discord.ui.button(label="Sisi Baik (Goodside)", style=discord.ButtonStyle.success, emoji="😇")
    async def good(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.send_modal(CSMainModal(self.server, "Goodside"))

    @discord.ui.button(label="Sisi Jahat (Badside)", style=discord.ButtonStyle.danger, emoji="😈")
    async def bad(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.send_modal(CSMainModal(self.server, "Badside"))

# --- STEP 0: PILIH SERVER DROPDOWN ---
class ServerSelect(discord.ui.Select):
    def __init__(self):
        options = [
            discord.SelectOption(label="JGRP", description="Buat CS untuk server JGRP.", emoji="🎮"),
            discord.SelectOption(label="SSRP", description="Buat CS untuk server State Side RP.", emoji="🇺🇸"),
            discord.SelectOption(label="Virtual RP", description="Buat CS untuk server Virtual RP.", emoji="💻"),
            discord.SelectOption(label="AARP", description="Buat CS untuk server Air Asia RP.", emoji="✈️"),
            discord.SelectOption(label="GCRP", description="Buat CS untuk server Grand Country RP.", emoji="🌳"),
            discord.SelectOption(label="Relative RP", description="Buat CS untuk server Relative RP.", emoji="👪"),
        ]
        super().__init__(placeholder="Pilih server tujuan...", options=options)

    async def callback(self, interaction: discord.Interaction):
        view = CSAlurView(self.values[0])
        embed = discord.Embed(
            title="🎭 Pilih Alur Cerita",
            description=f"Kamu memilih server: **{self.values[0]}**\nSekarang pilih sisi kehidupan karaktermu:",
            color=0x4287f5
        )
        await interaction.response.send_message(embed=embed, view=view, ephemeral=True)

class ServerSelectView(discord.ui.View):
    def __init__(self):
        super().__init__()
        self.add_item(ServerSelect())

# --- COMMANDS ---
@bot.command(name="panelcs")
async def panelcs(ctx):
    embed = discord.Embed(
        title="🚀 Tatang AI | Premium CS Generator",
        description=(
            "Halo! Silakan pilih server tujuan kamu terlebih dahulu melalui menu di bawah.\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "✨ **Fitur Baru v3.0**\n"
            "🔹 Pilihan Server Spesifik\n"
            "🔹 Alur Goodside & Badside\n"
            "🔹 Form Biodata Lengkap\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        ),
        color=0x5865f2
    )
    embed.set_thumbnail(url=ctx.author.display_avatar.url)
    embed.set_footer(text="Tatang Bot • Solusi Scripting & RP")
    await ctx.send(embed=embed, view=ServerSelectView())

# --- LAINNYA ---
@bot.tree.command(name="menu", description="Menu bot")
async def menu(interaction: discord.Interaction):
    # (Gunakan logika menu rapi yang sebelumnya)
    pass

if TOKEN:
    bot.run(TOKEN)
